ham2k/app-polo

- src/extensions/activities/pota/POTAAllParksData.js
- src/extensions/activities/wwff/WWFFDataFile.js
- src/extensions/activities/wwff/WWFFListItem.jsx
Fix based on existing code for SOTA in find one by reference, also applied to POTA for consistency.
> Fix crashing with WWFF with new database for references

- src/extensions/activities/eca/ECAActivityOptions.jsx
- src/extensions/activities/eca/ECADataFile.js
- src/extensions/activities/eca/ECAExtension.js
- src/extensions/activities/eca/ECAInfo.js
- src/extensions/activities/eca/ECAListItem.jsx
- src/extensions/activities/ela/ELAActivityOptions.jsx
- src/extensions/activities/ela/ELADataFile.js
- src/extensions/activities/ela/ELAExtension.js
- src/extensions/activities/ela/ELAInfo.js
- src/extensions/activities/ela/ELAListItem.jsx
- src/extensions/loadExtensions.js
This adds English Castles Awards (ECA) and English Lighthouse Awards (ELA) extensions.
ECA and ELA are similar to POTA in they allow multiple activations at once, with entities within 1km radius, but don't currently have a park-to-park like award so there is no "P2P" controls required.
> Add English Castles/Lighthouse Awards

- src/tools/geoTools.js
Simple fix of bearing currently being from other operator to you, rather than you to other operator
> Fix issue with bearing being in reverse

- src/extensions/activities/GMACommonPostSpot.js
Should only be additional references in comment
> Fix erroneously including main reference in GMA spot comment

- src/screens/SettingsScreens/screens/DataSettingsScreen.jsx
- src/store/operations/actions/operationsDB.js
When the list item is pressed, a dialog is shown to confirm.
> Add option to clear historical ADIF records

- src/extensions/activities/wwbota/WWBOTAActivityOptions.jsx
- src/extensions/activities/wwbota/WWBOTADataFile.js
- src/extensions/activities/wwbota/WWBOTAExtension.js
- src/extensions/activities/wwbota/WWBOTAInfo.js
- src/extensions/activities/wwbota/WWBOTAInput.jsx
- src/extensions/activities/wwbota/WWBOTAListItem.jsx
- src/extensions/activities/wwbota/WWBOTALoggingControl.jsx
- src/extensions/loadExtensions.js
- src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/CallInfo.jsx
Currently still using UKBOTA reference list, until confirmation of new WWBOTA reference list is available.
But this interim version properly handles WWBOTA references, and allows manual references to be entered for activation and B2B.
Todo:
> Change UKBOTA to Worldwide BOTA (WWBOTA)

- src/extensions/activities/eca/ECAExtension.js
This uses same logic as ELA as rules are the same (other than total QSO count).
> Fix ECA dupe checking

- src/extensions/activities/wwbota/WWBOTAExtension.js
This copies POTA/WWFF code for calculating `sameDay` in QSO scoring
> Fix new activity day calculation for WWBOTA

- src/extensions/activities/custom/CustomExtension.js
- src/extensions/activities/eca/ECAExtension.js
- src/extensions/activities/ela/ELAExtension.js
- src/extensions/activities/wwff/WWFFExtension.js
Some activity descriptions were missing longer description with name, and custom activity was only showing one reference.
> Fix some activity descriptions

- src/extensions/activities/eca/ECAExtension.js
- src/extensions/activities/ela/ELAExtension.js
- src/extensions/activities/siota/SiOTAExtension.js
- src/extensions/activities/wwbota/WWBOTAExtension.js
From 6ac7d64e197c6bb559ce64f6c77bfa111ac996e6
> Null leak in scoring when not in an operation ECA/ELA/SiOTA/WWBOTA

- src/extensions/activities/sota/SOTAExtension.js
- src/extensions/activities/sota/SOTAPostSpot.js
- src/store/apis/apiSOTA/apiSOTA.js
Reference changes announced at: https://reflector.sota.org.uk/t/upcoming-it-changes-mon-28th-oct-0000-utc/36601
> Update SOTA API to API-DB2

- src/extensions/activities/sota/SOTAExtension.js
QRT spots were filtered out, but where there was a normal spot and a QRT spot, the normal spot was still shown. This now dedupes spots first by callsign, resulting in QRT stations no longer being displayed (where QRT spot is most recent).
QRT spots is a feature of the new API.
> Filter out QRT stations for SOTA spots

- RELEASE-NOTES.json
- src/extensions/activities/wwbota/WWBOTAExtension.js
- src/store/apis/apiWWBOTA/apiWWBOTA.js
- src/store/apis/apiWWBOTA/index.js
- src/store/index.js
This fetches spots from WWBOTA cluster. This requires an extra library to parse the HTML to extract nonce value required to call the API.
> Add fetching of WWBOTA cluster spots

- src/store/apis/apiWWBOTA/apiWWBOTA.js
> Fix WWBOTA cluster

- RELEASE-NOTES.json
- src/extensions/other/wab/WABExtension.js
- src/extensions/other/wab/WABLocation.js
- src/extensions/other/wab/components/WABOpSetting.jsx
- src/extensions/other/wab/components/WABSquareDialog.jsx
Uses same grid as existing Worked All Britain Northern Ireland squares, so can reuse code and makes sense to just combine to one extension
> Add Worked All Ireland square

- RELEASE-NOTES.json
- src/extensions/activities/wwbota/WWBOTADataFile.js
- src/extensions/activities/wwbota/WWBOTAExtension.js
- src/extensions/activities/wwbota/WWBOTALoggingControl.jsx
Some minor fixes and improvements
> WWBOTA prefix guessing and cluster extract improvements

- src/extensions/contests/qp/parties/cpqp.json
- src/extensions/contests/qp/parties/de.json
- src/extensions/contests/qp/parties/ky.json
- src/extensions/contests/qp/parties/nm.json
- src/extensions/contests/qp/parties/wv.json
NM, DE, KY, and WV still need work
> Rules added

- src/extensions/contests/qp/parties/hi.json
- src/extensions/contests/qp/parties/md.json
Both have features that need to be implemented. See internalNotes.
> Added Rules - MDC & HI

- RELEASE-NOTES.json
- src/extensions/activities/mota/MOTAActivityOptions.jsx
- src/extensions/activities/mota/MOTADataFile.js
- src/extensions/activities/mota/MOTAExtension.js
- src/extensions/activities/mota/MOTAInfo.js
- src/extensions/activities/mota/MOTAInput.jsx
- src/extensions/activities/mota/MOTAListItem.jsx
- src/extensions/activities/mota/MOTALoggingControl.jsx
- src/extensions/activities/mota/MOTAPostSpot.js
- src/extensions/loadExtensions.js
- src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/CallInfo.jsx
Another popular program, supported by GMA
> Add Mills on the Air

- src/extensions/activities/wwff/WWFFPostSpot.js
To be remove in future and any errors are only logged to console for now
> Spot to GMA as well as new WWFF Spotline API

- RELEASE-NOTES.json
- src/extensions/activities/siota/PnPAccount.jsx
- src/extensions/activities/siota/SiOTAExtension.js
- src/extensions/activities/siota/SiOTAPostOtherSpot.js
- src/extensions/activities/siota/SiOTAPostSelfSpot.js
- src/store/apis/apiPnP/apiPnP.js
- src/store/apis/apiPnP/index.js
- src/store/index.js
Includes self and other spotting, and fetching spots for SiOTA
> Add spotting for SiOTA via ParksnPeaks

- RELEASE-NOTES.json
- src/extensions/activities/hsota/HSOTAActivityOptions.jsx
- src/extensions/activities/hsota/HSOTADataFile.js
- src/extensions/activities/hsota/HSOTAExtension.js
- src/extensions/activities/hsota/HSOTAInfo.js
- src/extensions/activities/hsota/HSOTAListItem.jsx
- src/extensions/loadExtensions.js
Added Canadian Historical Sites on the Air, as HSOTA.
Should allow support for other countries if the programme expands, although I've gone with maple leaf icon for now 🍁
> Add Historical Sites on the Air
