ham2k/app-polo

package-lock.json
package.json
src/extensions/loadExtensions.js
src/extensions/other/wab/WABExtension.js
src/extensions/other/wab/WABLocation.js
src/extensions/other/wab/components/WABOpSetting.jsx
src/extensions/other/wab/components/WABSquareDialog.jsx
src/extensions/registry.js
src/screens/OperationScreens/OpSettingsTab/OpSettingsTab.jsx

This requires additional package *proj4* for coordinate projection for identifying WAB square from latitude/longitude of device location.
This introduces a new hook for `opSettings` for per operation parameters. This felt like a better approach, as WAB isn't an activity as such, just fact of your location, and is something that is "hunted", and has no requirement to export/upload logs, etc.
Currently WAB square isn't export, but extension could be extended to include adding to `COMMENT` field in ADIF (as is of interest to hunter, not logger) or custom field.

Add support for WAB Square in Operation Info

---

src/extensions/activities/pota/POTAPostSpot.js

This will extend the user provided comment with, for example "2-fer: US-1234 US-4321" when activating more than one reference.

Include POTA park references in spot comment when activating multiple

---

src/extensions/activities/custom/CustomExtension.js
src/extensions/activities/pota/POTAExtension.js
src/extensions/activities/sota/SOTAExtension.js
src/extensions/activities/ukbota/UKBOTAActivityOptions.jsx
src/extensions/activities/ukbota/UKBOTADataFile.js
src/extensions/activities/ukbota/UKBOTAExtension.js
src/extensions/activities/ukbota/UKBOTAInfo.js
src/extensions/activities/ukbota/UKBOTAInput.jsx
src/extensions/activities/ukbota/UKBOTAListItem.jsx
src/extensions/activities/ukbota/UKBOTALoggingControl.jsx
src/extensions/activities/wwff/WWFFExtension.js
src/extensions/loadExtensions.js
src/screens/OperationScreens/OpLoggingTab/components/QSOItem.jsx
src/tools/qsonToADIF.js

Includes fetching public bunker list from official source (Google Drive); prefix guessing based on callsign; automatically adding slashes/dashes when inputting bunker to bunker.
There is no specific requirement for log uploading, so for simplicity of output, multiple B2Bs are comma separated in SIG_INFO.
Also transfers handling of "P2P" QSO item icons to extensions.
This also includes extension hook to add comments to ADI header. For UKBOTA in this case, includes details required for entry when submitting activation entry.

Add UKBOTA extension

---

src/extensions/other/wab/components/WABSquareDialog.jsx
src/screens/OperationScreens/OpSettingsTab/components/LocationDialog.js

I've noticed when in locations with poor coarse location due to lack of WiFi or phone signal, that grid squares can be incorrect without use of high accuracy with GPS, etc.
This isn't so much an issue when picking nearby parks/summits/…

Enable high accuracy location when getting grid squares

---

src/screens/OperationScreens/OperationAddActivityScreen.jsx

I found myself a couple of times pressing add activity when what I really wanted to do was to add a reference to an existing activity. And then when selecting the activity in the screen, it deletes all existing references, meaning they all have to be re-entered.

Filter out existing activities on Add Activity screen

---

src/extensions/activities/pota/POTAPostSpot.js

This changes so only first park is spotted, as seems that multi-spot isn't supported by POTA site due to being one spot per callsign, and therefore last park in the list takes precedence.

Only spot first park for POTA

---

RELEASE-NOTES.json
src/extensions/activities/eca/ECAExtension.js
src/extensions/activities/eca/ECAPostSpot.js
src/extensions/activities/ela/ELAExtension.js
src/extensions/activities/ela/ELAPostSpot.js

This spots at most once per activity type, similar to other activities, posting additional references in comments for n-fer activations, to avoid spamming the cluster.

Add spotting to GMA cluster for ECA/ELA activities

---

README.md
src/tools/timeFormats.js
src/tools/timeFormats.spec.js

This change will add the seconds part of the QSO timestamp when exporting to ADIF.

Include seconds in ADIF TIME_ON field

---

src/extensions/activities/GMACommonPostSpot.js
src/extensions/activities/pota/POTAPostSpot.js

This matches other behaviour with mode default to SSB if mode is ever undefined. Ideally mode wouldn't be undefined, but this covers just in case, consistent with rest of the app.

Default mode to SSB on spots if mode undefined

---

src/extensions/activities/wwbota/WWBOTADataFile.js

Input file is DOS file which ends each line with `\r\n` which was causing some issues with `\r` being pulled into header name (and grid).
Simple `trim()` on the row first removes this.

Fix parsing Maidenhead grid square with WWBOTA

---

android/app/build.gradle
package-lock.json
package.json
src/extensions/activities/sota/SOTAAccount.jsx
src/extensions/activities/sota/SOTAExtension.js
src/extensions/activities/sota/SOTAPostSpot.js
src/extensions/activities/sota/apiSOTA/apiSOTA.js
src/extensions/activities/sota/apiSOTA/index.js
src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/SecondaryExchangePanel.jsx
src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/SecondaryExchangePanel/SpotterControl.jsx
src/screens/SettingsScreens/screens/MainSettingsScreen.jsx
src/store/index.js

This includes addition of connecting to SOTA to enable self-spotting for SOTA activations.
Requires new dependency react-native-app-auth.
This is work in progress, as supports Android only currently.

Add ability to self-spot to SOTAWatch

---

src/extensions/activities/wwff/WWFFExtension.js
src/store/apiGMA/apiGMA.js
src/store/apiGMA/index.js
src/store/index.js

This adds WWFF spots from GMA API. The API code can also fetch general GMA spots, but this needs work to add code for identifying activity type. WWFF is special case that comes pre-filtered as is used on WWFFwatch on main WWFF site.

Add WWFF spots

---

src/store/apiSOTA/apiSOTA.js

SOTA API seems overly keen to assume account is logged out.
The fact that checking error message strings for connection errors isn't very robust, and more explicit check is probably required.
This adds a check that only flags account as logged out when an invalid grant error is returned. See below
> invalid_grant
>       The provided authorization grant (e.g., authorization
>       code, resource owner credentials) or refresh token is
>       invalid, expired, revoked, does not match the redirection
>       URI used in the authorization request, or was issued to
>       another client.

Only explicitly clear SOTA auth token on invalid_grant error

---

src/extensions/activities/gma/GMACommonPostSpot.js

Previously limited to those on web UI, but API documentation (and testing) shows it is free text, and should be valid ADIF mode.

Allow any mode on GMA cluster self-spots

---

src/extensions/activities/gma/GMAExtension.js
src/extensions/activities/siota/SiOTAExtension.js
src/extensions/activities/wwbota/WWBOTAExtension.js
src/extensions/activities/wwff/WWFFExtension.js
src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/CallInfo.jsx

Order is such that those that provide "value" come first, as this means new references for example, come before 0 point dupe messages for other activities.

Order scores by value for messages when logging

---

src/extensions/activities/gma/GMAExtension.js

SOTA summits are also valid for GMA activity, so can have duplicate filename with SOTA, producing only one log.
Whilst you could have just a SOTA log, as GMA accepts them, this would not enable GMA S2S where other summit is GMA and own in SOTA. So two logs are required.

Add "GMA" to GMA export filename

---

src/extensions/activities/sota/SOTAExtension.js

This was only checking for dupes if also on activation, and also the same reference check was failing

Fix issue with SOTA new ref and dupes on spots page

---

src/extensions/activities/wwbota/WWBOTAExtension.js

S5BOTA and Z3BOTA only need 10 QSOs for activation, rather than the usual 25

Correct activation counts for WWBOTA

---

src/store/apis/apiSOTA/apiSOTA.js

This is returned by SOTAWatch when token is expired, rather than 401 that comes from getting account info.

Handle SOTA token renewal on 500 error

---

src/extensions/activities/sota/SOTAExtension.js

Whilst PoLo was clever enough to realise frequency was in MHz, the ordering of spots page was broken. This changes freq to be in kHz for spots (like POTA and WWFF) to fix ordering.

Change SOTA spots frequency to kHz to fix spots ordering

---

src/screens/OperationScreens/OpSpotsTab/components/SpotItem.jsx
src/screens/OperationScreens/OpSpotsTab/components/SpotsPanel.jsx

This merges spots from multiple cluster where the callsign is the same, frequency is within 0.5kHz and time between spots less than 30mins. The most recent spot is primary, with additional refs and spot details added to it. Non-mergeable spots will be show separately as before
This also tweaks scoring of spots slightly, such that new refs are still highlight appropriately, for example operator activating 2 summits, but in same POTA, will show spot with new summit and SOTA icon highlight in green.
When logging QSO, all references are then saved as expected.
Merged example:
Worked all references:
New ref for one activity type, with new reference name taking preference:

Merge spots from multiple clusters

---

src/extensions/activities/sota/SOTAExtension.js

On highly active days, 50 is too small (about 15mins of spots during today's special event). Changing to 1 hour seems reasonable, and also stop really old spots on days of low activity.

Change SOTA spots limit from 50 to last hour

---

RELEASE-NOTES.json
src/extensions/data/hamqth/HamQTHAccount.jsx
src/extensions/data/hamqth/HamQTHExtension.js
src/extensions/loadExtensions.js
src/screens/OperationScreens/OpInfoTab/components/useCallLookup.js
src/store/apis/apiHamQTH/apiHamQTH.js
src/store/apis/apiHamQTH/index.js
src/store/apis/apiQRZ/apiQRZ.js
src/store/index.js

This adds HamQTH lookup for call data. This is a free service but requires login credentials.
This change includes a new account setting for entering log in details, and new API for HamQTH, which is very similar to QRZ.com API.
As part of this change there are also improved handling of lookup merging to ensure that when multiple lookups are done, that information is merged in priority order, but also stops high priority empty data taking preference of lower priority but present data.
This also resolved an issue with high priority data stopping lookup from other services, when that data was empty string e.g. grid from free QRZ.com lookup.

Add HamQTH lookup

---

src/store/apis/apiHamQTH/apiHamQTH.js

Grids are all uppercase from HamQTH and can be varying length. This ensures the 5th and 6th characters are lower case.

Fix grid format for HamQTH

---

src/screens/SettingsScreens/screens/MainSettingsScreen.jsx

This resolves issue with for example HamQTH or SOTA account settings not appearing if toggling on for the first time.
Reference https://forums.ham2k.com/t/minor-bug-hamqth-account-field-not-shown-after-activating/346

Refresh account settings hooks on settings change

---

src/screens/OperationScreens/OpSettingsTab/OperationDataScreen.jsx

Show station callsign when exporting logs.
| Before | After |
|-|-|
| ![image](https://github.com/user-attachments/assets/b6307388-4429-4b6d-a877-9a8ad7d68b56) | ![image](https://github.com/user-attachments/assets/cab4b98c-d1a3-4d24-8d83-3bc217641ab8) |

Use station call as fallback for subtitle

---

src/extensions/scoring/DefaultScoringHandler.js
src/screens/OperationScreens/OpSettingsTab/OperationDataScreen.jsx
src/store/operations/actions/dataExchangeActions/importADIF.js

This uses existing default score handler, with minor change that identical timestamps (which occur when importing same adif) qualify as dupe.
If preferable, could add custom dedupe logic.

Add deduping on ADIF import for operations

---

src/extensions/activities/sota/SOTAExtension.js

On my last activation, I started a QSO with a SOTA operator and couldn't complete it, but accidentally hit the Save button. I then went back and deleted the QSO.
When it came to export my logs, PoLo suggested to export a SOTA hunter log. When I tried this, the file was (correctly) empty. However, I think the suggestion to export the log shouldn't have been there.
This patch fixes the issue, meaning that for the SOTA hunter log to be recommended, you must have QSOs with SOTA references _and_ those QSOs must be non-deleted.

Don't suggest exporting a SOTA hunter log if the only SOTA QSOs are deleted

---

src/extensions/activities/pota/POTAExtension.js
src/screens/OperationScreens/OpSpotsTab/OpSpotsTab.jsx

This utilises the known structure of the spots from fellow Ham2k PoLo users to fetch their extra park references when hunting.
As this requires extra calls to POTA API, it's just too slow to do when POTA returning 100s of spots, so this added feature is only used when selecting a spot.
https://github.com/user-attachments/assets/8e050815-51b0-4526-8af8-46ff486617a0

Attempt to fetch multiple references for POTA spots

---

src/extensions/activities/pota/POTAConfirmFromSpots.js
src/store/qsos/actions/confirmFromSpots.js

Made some tweaks to how confirming spots works:
1. Removed spots that match the current station to avoid suggesting your own call
2. Reduced sensitivity so only 2 characters can be wrong to suggest a new call
3. Don't suggest a spot if it matches an existing log entry
- Example:
- Log QSOs: [AB1CD, AB2CD, WF1XZ]
- Spots: [AB1CD]
- Only AB1CD is marked as confirmed, AB2CD would not offer a suggestion to correct to AB1CD even if its distance is 1, because AB1CD is a correct call in the log.
4. Store spot comment as a note

Confirm spots improvements

---

src/extensions/scoring/index.js

As scoring handlers for general hunting are always added, the handlers array wasn't empty to check for adding default score handler. Simply moved this check to post adding activty based handlers.

Fix general operation scoring / duplicate flagging

---

src/extensions/activities/pota/POTAExtension.js

In some cases, for example "K-TEST" park, states has invalid data, and such the trim can fail being called on undefined.

Handle case where POTA states is not valid

---

src/store/qsos/actions/confirmFromSpots.js

This will save the notes from the spots to the QSOs so they can be exported.

Persist spot confirmations to DB

---

src/screens/OperationScreens/OpSettingsTab/OpSettingsTab.jsx
src/screens/OperationScreens/OpSettingsTab/OperationDataScreen.jsx
src/screens/OperationScreens/OpSettingsTab/components/ExportWavelogDialog.jsx
src/screens/SettingsScreens/screens/CreditsSettingsScreen.jsx
src/screens/SettingsScreens/screens/DevModeSettingsScreen.jsx
src/screens/SettingsScreens/screens/MainSettingsScreen.jsx
src/screens/SettingsScreens/screens/WavelogSettingsScreen.jsx
src/tools/qsonToWavelog.js

Adds Wavelog Export support natively into the app:
Configure Station/URL/Api Key inside settings:
Export QSOS to wavelog from operation tab:

Add Wavelog Support
